export const profilePost = [
  {
    id: 1,
    type: "multiple",
    img: "https://images.unsplash.com/photo-1554080353-a576cf803bda?ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8cGhvdG98ZW58MHx8MHx8&ixlib=rb-1.2.1&w=1000&q=80",
    like: 12,
    comment: 2,
  },
  {
    id: 2,
    type: "video",
    img: "https://github.com/bricesuazo.png",
    like: 12,
    comment: 5,
  },
  {
    id: 3,
    type: "photo",
    img: "https://images.pexels.com/photos/9896250/pexels-photo-9896250.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    like: 120,
    comment: 2,
  },
  {
    id: 4,
    type: "multiple",
    img: "https://images.pexels.com/photos/8971125/pexels-photo-8971125.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    like: 12,
    comment: 2,
  },
  {
    id: 5,
    type: "multiple",
    img: "https://images.unsplash.com/photo-1554080353-a576cf803bda?ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8cGhvdG98ZW58MHx8MHx8&ixlib=rb-1.2.1&w=1000&q=80",
    like: 12,
    comment: 2,
  },
  {
    id: 6,
    type: "video",
    img: "https://github.com/bricesuazo.png",
    like: 12,
    comment: 2,
  },
  {
    id: 7,
    type: "photo",
    img: "https://images.pexels.com/photos/9896250/pexels-photo-9896250.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    like: 12,
    comment: 2,
  },
  {
    id: 8,
    type: "multiple",
    img: "https://images.pexels.com/photos/8971125/pexels-photo-8971125.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    like: 12,
    comment: 2,
  },
];

export const storyData = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    username: "Your Story",
    seen: true,
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    username: "brice_suazo",
    seen: false,
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/1040881/pexels-photo-1040881.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    username: "junarbenturog",
    seen: false,
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/697509/pexels-photo-697509.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    username: "masterjunar",
    seen: false,
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/9902417/pexels-photo-9902417.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    username: "jamesreid",
    seen: false,
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    username: "brice_suazo",
    seen: false,
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/1040881/pexels-photo-1040881.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    username: "junarbenturog",
    seen: false,
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/697509/pexels-photo-697509.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    username: "masterjunar",
    seen: false,
  },
  {
    id: 9,
    img: "https://images.pexels.com/photos/9902417/pexels-photo-9902417.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    username: "jamesreid",
    seen: false,
  },
];

export const postData = [
  {
    id: 1,
    type: "multiple",
    username: "brice_suazo",
    location: "Cavite, Philippines",
    profilePicture: "https://github.com/bricesuazo.png",
    postedMedia: [
      "https://images.pexels.com/photos/9884589/pexels-photo-9884589.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "https://images.pexels.com/photos/9902408/pexels-photo-9902408.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    ],
    likes: 1200,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias facere odit nulla culpa eos repellendus cumque expedita veritatis, similique laudantium.",
    comments: ["nice", "lol"],
    dateUploaded: new Date(),
  },
  {
    id: 2,
    type: "single",
    username: "master_junar",
    location: "",
    profilePicture:
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    postedMedia: [
      "https://images.pexels.com/photos/9884589/pexels-photo-9884589.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "https://images.pexels.com/photos/9902408/pexels-photo-9902408.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    ],
    likes: 1200,
    desc: "This data is coming from the dummyData.js",
    comments: ["nice", "lol", "wews"],
    dateUploaded: new Date(),
  },
];

export const inboxData = [
  {
    id: 1,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: "• 1d",
  },
  {
    id: 2,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 1h ago",
    time: "• 5w",
  },
  {
    id: 3,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Replied to you story:",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
  {
    id: 4,
    profilePicture: "https://github.com/bricesuazo.png",
    username: "brice_suazo",
    desc: "Active 44m ago",
    time: null,
  },
];
